version: '3'
services:
  web:
    image: vxztu2/0726kng
    ports:
      - "8000:8000"
    volumes:
      - ./ssl:/app/ssl
    environment:
      - DEBUG=0
      - SECRET_KEY=your_secret_key_here
      - DATABASE_URL=mysql://user:password@db:3306/dbname
    depends_on:
      - db
  
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

volumes:
  mysql_data:
