FROM python:3.10
RUN apt-get update && apt-get install -y git
WORKDIR /app

# Git 저장소 클론 (서브모듈 포함)
ARG REPO_URL
RUN git clone --recursive ${REPO_URL} .

# 필요한 패키지 설치
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 실행 명령
CMD ["gunicorn", "vod.wsgi:application", "--bind", "0.0.0.0:8000"]
