FROM python:3.10

WORKDIR /app

# 필요한 패키지 설치
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 소스 코드 복사
COPY . .

# 실행 명령
CMD ["gunicorn", "vod.wsgi:application", "--bind", "0.0.0.0:8000"]
