FROM python:3.10
# Git 설치 (서브모듈을 위해 필요)
RUN apt-get update && apt-get install -y git
WORKDIR /app
# 소스 코드와 .git 디렉토리 복사
COPY . . 
# 서브모듈 초기화 및 업데이트
RUN git submodule update --init --recursive
# 필요한 패키지 설치
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
# 실행 명령
CMD ["gunicorn", "vod.wsgi:application", "--bind", "0.0.0.0:8000"]

