version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - SECRET_KEY=your_secret_key_here
      - DATABASE_URL=mysql://projectadmin:projectuserpassword@db:3306/project_24kng
    depends_on:
      - db
    
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=project_24kng
      - MYSQL_USER=projectadmin
      - MYSQL_PASSWORD=projectuserpassword
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  mysql_data:
  static_volume:
  media_volume:
