services:
  db01:
    image: mariadb
    hostname: db
    container_name: db01
    environment:
      MARIADB_USER: yoyo
      MARIADB_PASSWORD: abcd
      MARIADB_DATABASE: cloud_db
      MARIADB_ROOT_PASSWORD: abcd1234
    volumes:
      - $PWD/mariadb:/var/lib/mysql

  was01:
    build: 
      context: ./dockers
      dockerfile: django.docker

    hostname: was
    container_name: was01
    ports:
      - 8000:8000
    environment:
      MARIADB_USER: yoyo
      MARIADB_PASSWORD: abcd
      MARIADB_DATABASE: cloud_db
      MARIADB_HOST: db
      MARIADB_PORT: 3306
    volumes:
      - .:/code
    depends_on:
      - db01

    command: ["gunicorn", "--bind", "0.0.0.0:8000", "mysite1.wsgi:application"]

  nginx:
      image: nginx:latest
      container_name: nginx
      ports:
        - "80:80"
      volumes:
        - ./nginx/conf/:/etc/nginx/conf.d/
        - ./nginx/static/:/var/www/static/
      depends_on:
        - was01
      restart: always