name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  DOCKER_IMAGE: kaseykim7123/24kng_webpages
  ARGOCD_REPO: kkkikki/24KNG_argocd
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install Pillow
        pip install -r requirements.txt
        pip install mysqlclient
        sudo apt-get update
        sudo apt-get install -y libmysqlclient-dev
    - name: Run tests
      run: python ./vod/manage.py test
  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: Build Docker image
      run: |
        docker build -t ${{ env.DOCKER_IMAGE }}:${{ github.sha }} .
        docker build -t ${{ env.DOCKER_IMAGE }}:latest .
      working-directory: ./vod
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push Docker image
      run: |
        docker push ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
        docker push ${{ env.DOCKER_IMAGE }}:latest
  update-argocd-repo:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ env.ARGOCD_REPO }}
        token: ${{ secrets.ARGOCD_REPO_TOKEN }}
        fetch-depth: 1
        path: argo-repo
    - name: Verify deployments.yaml exists
      run: |
        if [ ! -f argo-repo/kubernetes/deployments.yaml ]; then
          echo "File not found!"
          exit 1
        fi
    - name: Update Kubernetes manifests
      run: |
        sed -i 's|image: .*|image: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}|' argo-repo/kubernetes/deployments.yaml
    - name: Commit and push changes
      run: |
        cd argo-repo
        git config --global user.name "kkkikki"
        git config --global user.email "kaseykim7123@gmail.com"
        git add kubernetes/deployments.yaml
        git commit -m "Update image to ${{ github.sha }}"
        git push